[workspace]
authors = ["jsbyysheng <jsbyysheng@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "20250423_ZL_PhD_scAnalysis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = "1.26.4.*"
scipy = "1.13.*"
pandas = "2.2.2.*"
polars = "==0.20.31"
scanpy = "1.10.*"
ipywidgets = ">=8.1.6,<9"
matplotlib = ">=3.9.1,<4"
h5py = ">=3.13.0,<4"
joblib = ">=1.5.0,<2"
ipykernel = ">=6.29.5,<7"
tqdm = ">=4.67.1,<5"
pyahocorasick = ">=2.1.0,<3"

[feature.cellranger.dependencies]
python = "3.9.*"
pyyaml = ">=6.0.2,<7"
lz4 = ">=4.4.4,<5"
numexpr = ">=2.10.2,<3"

[feature.py311.dependencies]
python = "3.11.*"
gtfparse = ">=2.5.0,<3"
pyfastx = ">=2.2.0,<3"
snakemake = ">=9.4.0"
umi_tools = ">=1.1.6,<2"
star = ">=2.7.11b,<3"
cutadapt = ">=5.0,<6"
fastq = ">=2.0.4,<3"
minifasta = ">=3.0.2,<4"

[pypi-dependencies]
toolbox = { path = "mylibs/toolbox", extras = ["all"], editable = true}
martian = ">=2.1, <3"
tables = ">=3.9.2, <4"

[environments]
default = ["py311"]
cellranger = ["cellranger"]
